### ISSUE TITLE
`TODO` | Client-side UI

### ISSUE THREAD

**Issue by ETCasual** [marcustut/lightchaser#2]
**Overall Game**
- [x] countdown timer
- [ ] Announcement dialog / notification panel

**Interactive**
- [x] L5 attendance
- [x] Attendance scanning
- [x] Interaction
- [x] Reaction
- [ ] Admin UI

**Score / Ranking**
- [ ] GM Scanner
- [ ] Group QR
- [ ] Leaderboard

**Tech Game**
- [x] Dashboard
- [x] Mall Checkout
- [ ] AR Camera
- [ ] PIN
- [ ] Wallet
- [ ] L5 QR into dashboard
- [ ] L5 multiple QR for games

**Comment by ETCasual** [comment]
I will be using the bolded text to act as `branch_name` when pushed
